# See for https://github.com/github/licensed/blob/master/docs/configuration.md for more details.
# If not set, defaults to the directory name of `source_path`
name: 'cli-kintone'

# Sources of metadata
sources:
  npm: true

# Dependencies with these licenses are allowed and will not raise errors or warnings.
# This list does not have a default value and is required for `licensed status`
# to succeed.
allowed:
  - mit
  - apache-2.0
  - bsd-3-clause
  - isc

# These dependencies are ignored during enumeration.
# They will not be cached, and will not raise errors or warnings.
# This configuration is intended to be used for dependencies that don't need to
# be included for compliance purposes, such as other projects owned by the current
# project's owner, internal dependencies, and dependencies that aren't shipped with
# the project like test frameworks.
#ignored:
#  bundler:
#    - some-internal-gem
#
#  bower:
#    - some-internal-package

# These dependencies have licenses not on the `allowed` list and have been reviewed.
# They will be cached and checked, but will not raise errors or warnings for a
# non-allowed license.  Dependencies on this list will still raise errors if
# license text cannot be found for the dependency.
reviewed:
  npm:
    - color-convert # MIT
