# See for https://github.com/github/licensed/blob/master/docs/configuration.md for more details.
# If not set, defaults to the directory name of `source_path`
name: 'cli-kintone'

# Sources of metadata
sources:
  npm: true

# Dependencies with these licenses are allowed and will not raise errors or warnings.
# This list does not have a default value and is required for `licensed status`
# to succeed.
allowed:
  - mit
  - apache-2.0
  - bsd-3-clause
  - isc
  - 0bsd

# These dependencies are ignored during enumeration.
# They will not be cached, and will not raise errors or warnings.
# This configuration is intended to be used for dependencies that don't need to
# be included for compliance purposes, such as other projects owned by the current
# project's owner, internal dependencies, and dependencies that aren't shipped with
# the project like test frameworks.
#ignored:
#  bundler:
#    - some-internal-gem
#
#  bower:
#    - some-internal-package

# These dependencies have licenses not on the `allowed` list and have been reviewed.
# They will be cached and checked, but will not raise errors or warnings for a
# non-allowed license.  Dependencies on this list will still raise errors if
# license text cannot be found for the dependency.
reviewed:
  npm:
    - color-convert # MIT
    - bl # MIT
    - wcwidth # MIT
    - type-fest # MIT OR CC0-1.0
    - string_decoder # MIT
    - string_decoder # MIT
    - readable-stream # MIT
    - lodash # MIT
    - ieee754 # BSD-3-Clause
    - "@npmcli/fs" # ISC
    - "@pkgjs/parseargs" # apache-2.0
    - abbrev # ISC
    - are-we-there-yet # ISC
    - cacache # ISC
    - encoding # MIT
    - gauge # ISC
    - glob # ISC
    - http-cache-semantics # BSD 2-Clause
    - jackspeak # BlueOak-1.0.0
    - make-fetch-happen # ISC
    - minipass-fetch # MIT
    - minizlib
    - npmlog # ISC
    - path-scurry # BlueOak-1.0.0
    - retry # apache-2.0
    - ssri # ISC
    - fs.realpath # ISC
