packages:
  - "website"

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  # Renovate security update: tar@7.5.7 || 7.5.8
  - tar@7.5.7 || 7.5.8
  # Renovate security update: ajv@8.18.0
  - ajv@8.18.0
