version: 2.1

commands:
  run-npm-test:
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      # run tests!
      - run: npm test
jobs:
  node-v6:
    docker:
      - image: circleci/node:6@sha256:925edb2ca895415a6ef5cbf4452a3baf4e8e2e0b2c7ba7bfc79fbdf6d972d8df
    steps:
      - run-npm-test
  node-v8:
    docker:
      - image: circleci/node:8@sha256:38fa37bea9f5e55accb9290d6789bb5e29618f12d89ae54eee5e2db974a2c6e5
    steps:
      - run-npm-test
  node-v10:
    docker:
      - image: circleci/node:10@sha256:a38508c2ad622c1bdbdacaa7cdc386cddbdedb735599cfb8c854b7d7b78258d3
    steps:
      - run-npm-test

workflows:
  multiple_builds:
    jobs:
      - node-v6
      - node-v8
      - node-v10
