version: 2.1

commands:
  run-npm-test:
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      # run tests!
      - run: npm run lint
      - run: npm run test:all
jobs:
  node-v8:
    docker:
      - image: circleci/node:8@sha256:4c1baf47957206f7a98c988847de0efc25e7db8a0dfd45cce62525b7debb0e3f
    steps:
      - run-npm-test
  node-v10:
    docker:
      - image: circleci/node:10@sha256:1399468d2d47facd4916566091de6a34006d9cc2a6276c5aff35a1532eb15a8c
    steps:
      - run-npm-test
  node-v12:
    docker:
      - image: circleci/node:12
    steps:
      - run-npm-test

workflows:
  multiple_builds:
    jobs:
      - node-v8
      - node-v10
      - node-v12
