version: 2.1

commands:
  run-npm-test:
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      # run tests!
      - run: npm test
jobs:
  node-v6:
    docker:
      - image: circleci/node:6@sha256:bd4d26b3518b91b43c405d3431f7af5e4d8c97c94cee3f0b6acdf3cd1e893d71
    steps:
      - run-npm-test
  node-v8:
    docker:
      - image: circleci/node:8@sha256:e4a14d476ccc5369afa6a8e89a5705771c2bafc4557599dcda87a397b7db5806
    steps:
      - run-npm-test
  node-v10:
    docker:
      - image: circleci/node:10@sha256:30c182fc148b4b1be18db2f34502e009aa70378df036702769e6d29eda1079cf
    steps:
      - run-npm-test

workflows:
  multiple_builds:
    jobs:
      - node-v6
      - node-v8
      - node-v10
