version: 2.1

commands:
  run-npm-test:
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      # run tests!
      - run: npm test
jobs:
  node-v6:
    docker:
      - image: circleci/node:6@sha256:0bd2762e99fce6f6b2687d7202ebfe99bf5c00567ba81cc59ea7911d086f9e5b
    steps:
      - run-npm-test
  node-v8:
    docker:
      - image: circleci/node:8@sha256:5da5d585c88fb16f3c5eb449b80626ec6ae0e626a75d1b798749ea8d589ac8e9
    steps:
      - run-npm-test
  node-v10:
    docker:
      - image: circleci/node:10@sha256:3371d450f106db5dc28256b52750c6af6a7099776af9bf8762a6941780ad97de
    steps:
      - run-npm-test

workflows:
  multiple_builds:
    jobs:
      - node-v6
      - node-v8
      - node-v10
