# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo

  steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package-lock.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: npm install

    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package-lock.json" }}
      
    # run tests!
    - run: npm run lint
    - run: npm run test:all

jobs:
  node-v6:
    <<: *defaults
    docker:
      - image: circleci/node:6@sha256:921254e5cca448bc360ba619414de58254000d78b2b73def0bbed81caf5cd4b5
  node-v8:
    <<: *defaults
    docker:
      - image: circleci/node:8@sha256:a629192e19e872866a038cb56cc81bf7d43a0e01915e97c190e4ab9ab9dfa200
  node-v10:
    <<: *defaults
    docker:
      - image: circleci/node:10

workflows:
  version: 2
  multiple_builds:
    jobs:
      - node-v6
      - node-v8
      - node-v10