version: 2.1

commands:
  run-npm-test:
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      # run tests!
      - run: npm test
jobs:
  node-v6:
    docker:
      - image: circleci/node:6@sha256:a6dde758b6dac40538e4b562983536399bc675ba7c9ddf12362c3f76af8b073d
    steps:
      - run-npm-test
  node-v8:
    docker:
      - image: circleci/node:8@sha256:17834d747d6197afc3053fffcbc1121a02d9111db11f27543130ac37ee13825f
    steps:
      - run-npm-test
  node-v10:
    docker:
      - image: circleci/node:10@sha256:2c2384d6485f190673b4873ae05828123f4da3f3611f7899fb2f853e51eba486
    steps:
      - run-npm-test

workflows:
  multiple_builds:
    jobs:
      - node-v6
      - node-v8
      - node-v10
