version: 2.1

commands:
  run-npm-test:
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      # run tests!
      - run: npm run lint
      - run: npm run test:all
jobs:
  node-v8:
    docker:
      - image: circleci/node:8@sha256:e4ce1076480b0ac61f16e89a2b3266ab4056a4dd83e22d99a2b39ebc3231170f
    steps:
      - run-npm-test
  node-v10:
    docker:
      - image: circleci/node:10@sha256:16596715edb0d9c08441aaf9b8d8766863f4eca0c0aff3cb920a19baa0a01c53
    steps:
      - run-npm-test
  node-v12:
    docker:
      - image: circleci/node:12
    steps:
      - run-npm-test

workflows:
  multiple_builds:
    jobs:
      - node-v8
      - node-v10
      - node-v12
