version: 2.1

commands:
  run-npm-test:
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      # run tests!
      - run: npm test
jobs:
  node-v6:
    docker:
      - image: circleci/node:6@sha256:cdb5d5997a7ff4fb2978932786038fa95c1fab46d5a081784c25887d7ac7cb3d
    steps:
      - run-npm-test
  node-v8:
    docker:
      - image: circleci/node:8@sha256:fa335a5e6518c937e4e261e79158a69c9a4c855fbc38bea89e6da720f63a3177
    steps:
      - run-npm-test
  node-v10:
    docker:
      - image: circleci/node:10@sha256:0d8db53ca1714322f6cb492155944b2deebbd7dc45f9345655baae9e0dcad2b7
    steps:
      - run-npm-test

workflows:
  multiple_builds:
    jobs:
      - node-v6
      - node-v8
      - node-v10
