version: 2.1

commands:
  run-npm-test:
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      # run tests!
      - run: npm run lint
      - run: npm run test:all
jobs:
  node-v8:
    docker:
      - image: circleci/node:8@sha256:b2ca3bbcea15ef61f2423ab693cac6731776e8aed0a5ea01e0aec830e2e35ca9
    steps:
      - run-npm-test
  node-v10:
    docker:
      - image: circleci/node:10@sha256:c1097f66867cc627b59b4f8975452c18a8d7d1539d345abe23f6b33bfd6d45a7
    steps:
      - run-npm-test
  node-v12:
    docker:
      - image: circleci/node:12
    steps:
      - run-npm-test

workflows:
  multiple_builds:
    jobs:
      - node-v8
      - node-v10
      - node-v12
