version: 2.1

commands:
  run-npm-test:
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      # run tests!
      - run: npm test
jobs:
  node-v6:
    docker:
      - image: circleci/node:6@sha256:f0cfe896ff27b843ac5686ec59fe7e161e23394f853306d6eb11d1d958165c77
    steps:
      - run-npm-test
  node-v8:
    docker:
      - image: circleci/node:8@sha256:c81e5c1471c1012822dc92bb3c787118550e5e038b4807c9a9626f0d5deeb0b5
    steps:
      - run-npm-test
  node-v10:
    docker:
      - image: circleci/node:10@sha256:496ee37950d199f1525fa51393f76ab25b880a6db0e64e1209f81ced120b8254
    steps:
      - run-npm-test

workflows:
  multiple_builds:
    jobs:
      - node-v6
      - node-v8
      - node-v10
