version: 2.1

commands:
  run-npm-test:
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      # run tests!
      - run: npm test
jobs:
  node-v6:
    docker:
      - image: circleci/node:6@sha256:c9cfdf4a8475efae1d22e1c70c5502516a9a7c9115da71f92c94739813822110
    steps:
      - run-npm-test
  node-v8:
    docker:
      - image: circleci/node:8@sha256:b0b6b8d233527835f1a4617a73dfc589d022db127f6cb59718e36890cfc2e623
    steps:
      - run-npm-test
  node-v10:
    docker:
      - image: circleci/node:10@sha256:5ce09739b7332f583aefcfb5ef45fa46dbe2445ae59e396089e4647b3d2169e3
    steps:
      - run-npm-test

workflows:
  multiple_builds:
    jobs:
      - node-v6
      - node-v8
      - node-v10
