version: 2.1

commands:
  run-npm-test:
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      # run tests!
      - run: npm test
jobs:
  node-v6:
    docker:
      - image: circleci/node:6@sha256:f51b7c01b84d112d7e9ba600ffa43610b97f1176655951d9114acdd71f496cbe
    steps:
      - run-npm-test
  node-v8:
    docker:
      - image: circleci/node:8@sha256:56d8e1749473c18dbcd1689bad2174ba848ba5b7eb45203dd8e8f7f48feed766
    steps:
      - run-npm-test
  node-v10:
    docker:
      - image: circleci/node:10@sha256:06c9588f80024757c92e9f50f879be6444dc6be690f32c06c3904da500d8d4e7
    steps:
      - run-npm-test

workflows:
  multiple_builds:
    jobs:
      - node-v6
      - node-v8
      - node-v10
