version: 2.1

commands:
  run-npm-test:
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      # run tests!
      - run: npm test
jobs:
  node-v6:
    docker:
      - image: circleci/node:6@sha256:d84ab73972cc24b1585042f3f03a3e7b9f8ff6248aa81f8bd00318d7cdef1385
    steps:
      - run-npm-test
  node-v8:
    docker:
      - image: circleci/node:8@sha256:7c857f954d0cb36afda0be8cef448813a819575ef2eefb88fc6a2a2bb9ba76e3
    steps:
      - run-npm-test
  node-v10:
    docker:
      - image: circleci/node:10@sha256:8b4e26fc21ccde3c5ab2eb60fb4ec22e3e71aa497e5f1121e3209cdebc5efe6f
    steps:
      - run-npm-test

workflows:
  multiple_builds:
    jobs:
      - node-v6
      - node-v8
      - node-v10
