version: 2.1

commands:
  run-npm-test:
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      # run tests!
      - run: npm run lint
      - run: npm run test:all
jobs:
  node-v8:
    docker:
      - image: circleci/node:8@sha256:302860c78743e6e57f865c2ca5720ac26bc78180ada08f20518aa9fec80e3fc2
    steps:
      - run-npm-test
  node-v10:
    docker:
      - image: circleci/node:10@sha256:5c170adade985597275f2184b21bee6420e386522a725ecb76fe3905a9730d81
    steps:
      - run-npm-test
  node-v12:
    docker:
      - image: circleci/node:12
    steps:
      - run-npm-test

workflows:
  multiple_builds:
    jobs:
      - node-v8
      - node-v10
      - node-v12
