name: "🐛 Bug report"
description: Report a reproducible bug of cli-kintone
labels: ["bug"]
title: "[Bug] "
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the followings.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Please describe what the bug is.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Target Version
      placeholder: e.g. vX.Y.Z
      description: Which version of cli-kintone do you want to report a bug for?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: |
        Please provide [minimum reproduction](https://stackoverflow.com/help/minimal-reproducible-example) steps of the bug.
        If you have a reproduction repository, [GitHub Gist](https://gist.github.com/) snippet, or some external pages, please share the links.

        :warning: DO NOT SUBMIT CONFIDENTIAL INFORMATION SUCH AS YOUR SUBDOMAIN AND PASSWORD
      placeholder: |
        1. Prepare a Kintone App with the following fields...
        2. Run cli-kintone with the following options...
        ...
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What is the behavior you expected?
    validations:
      required: true
  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What is the actual behavior you saw?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    id: os
    attributes:
      label: Operation System (if relevant)
      placeholder: e.g. Windows 10
      description: What Operating system did the bug occur on?
    validations:
      required: false
  - type: input
    id: shell
    attributes:
      label: Shell (if relevant)
      placeholder: e.g. zsh 5.9
      description: What shell did the bug occur on?
    validations:
      required: false
