name: "🚀 Feature Request"
description: Propose a feature improvement of cli-kintone
labels: ["feature request"]
title: "[Feature Request] "
body:
  - type: markdown
    attributes:
      value: |
        Thank you for sending a feature request! Please fill out the followings.
  - type: textarea
    id: why
    attributes:
      label: Why
      description: Why do you want the feature, and why should it be in the package?
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: What
      description: What is a solution you want to add?
    validations:
      required: true
