name: "🐛 Bug report"
description: Report for reproducible bug of cli-kintone
labels: ["bug"]
title: "[Bug] "
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug!
        Please fill out the following.
  - type: input
    id: version
    attributes:
      label: Target Version
      placeholder: e.g. vX.Y.Z
      description: Which version of cli-kintone do you want to report a bug for? 
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operation System (if relevant)
      placeholder: e.g. Windows 10
      description: What Operating system did the bug occur on?
    validations:
      required: false
  - type: input
    id: shell
    attributes:
      label: Shell (if relevant)
      placeholder: e.g. zsh 5.9
      description: What shell did the bug occur on?
    validations:
      required: false
  - type: input
    id: reproduction
    attributes:
      label: Link To Reproduction
      description: |
        Please provide a link to a [minimum reproduction](https://stackoverflow.com/help/minimal-reproducible-example). A repository or [GitHub Gist](https://gist.github.com/) is preferred.
      placeholder: Reproduction URL
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What is the behavior you expected?
    validations:
      required: true
  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What is the actual behavior you saw?
    validations:
      required: true
