name: License

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  analyze-and-extract:
    name: Analyze and extract licenses
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@54d513e0b5ff1158f1cf8321108d666a5a6c1fca # v2

      - name: Check out repository
        uses: actions/checkout@v5

      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6

      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"

      - uses: flatt-security/setup-takumi-guard-npm@9a5d797c2085b6326d3a2985c08e3a114b9b88c1 # v1.1.1
        with:
          bot-id: ${{ !github.event.pull_request.head.repo.fork && secrets.TAKUMI_GUARD_BOT_ID || '' }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check licenses
        run: |
          pnpm license:analyze
          pnpm license:extract
