name: Node CI on windows

on: [push]

jobs:
  test:

    runs-on: windows-2019

    strategy:
      matrix:
        node-version: [8.16, 10, 12]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # can not use multi-line step run
    # https://github.community/t5/GitHub-Actions/Windows-multi-line-step-run/td-p/30428
    - run: node --version 
    - run: npm --version
    - run: npm ci
    - run: npm test
