name: test-npm

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  prepare:
    name: Prepare npm package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm pack
      - run: mv kintone-cli-*.tgz kintone-cli.tgz
      - uses: actions/upload-artifact@v5
        with:
          name: kintone-cli.tgz
          path: kintone-cli.tgz

  test-install:
    name: Test npm install - Node.js ${{ matrix.os }} ${{ matrix.node-version }}
    needs: prepare
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [20, 22, 24]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/download-artifact@v6
        with:
          name: kintone-cli.tgz
      - run: npm install -g kintone-cli.tgz
      - run: cli-kintone --version

  test-npx:
    name: Test npx - Node.js ${{ matrix.os }} ${{ matrix.node-version }}
    needs: prepare
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [20, 22, 24]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/download-artifact@v6
        with:
          name: kintone-cli.tgz
      - run: npx kintone-cli.tgz --version
